data:
    BSZ: 80
    bptt_len: 70
    vocabSize: 28913
    data_root: '/home/xieliang/Data'
    save_root: '/home/xieliang/Data/LM'
    fasttext_root: '/home/xieliang/Data/fasttext'
model:
    rnn:
        nemd: 300
        nhid: 1150
        nlayer: 3
        embed_drop_ratio: 0.2
        locked_drope: 0.65
        locked_droph: 0.2
        locked_dropo: 0.4
        alpha: 2
        beta: 1
        tie_weight: True
        rnn_type: 'LSTM'
        pretrained_embedding: True
    transformer:
        nemd: 100
        nhid: 256
        nlayer: 2
        nhead: 2
        emd_drop_ratio: 0
        hidden_drop_ratio: 0
        tie_weight: False
training:
    model_type: 'rnn'
    optim_type: 'sgd'
    lr: 30
    weight_decay: 0.0000012
    momentum: 0
    grad_clip: 0.25
    lr_decay_factor: 1.0
